import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/global/Navbar"
import Footer from "@/components/global/Footer"

const inter = Inter({
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn("dark h-full antialiased", inter.className)}
        suppressHydrationWarning
      >
        <main className="flex flex-col h-full min-h-screen">
          <Navbar />
          <div className="flex-grow flex-1">{children}</div>
          <Footer />
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  )
}
