import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"

const inter = Inter({
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn("h-full antialiased", inter.className)}>
        <main className="flex flex-col h-full min-h-screen">
          {/* <Navbar /> */}
          <div className="flex-grow flex-1">{children}</div>
          {/* <Footer /> */}
        </main>
        {/* <Toaster position="top-center" richColors /> */}
      </body>
    </html>
  )
}
